//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickRecordEditor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class SettingsVariables : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsVariables defaultInstance = ((SettingsVariables)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsVariables())));
        
        public static SettingsVariables Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Image32Base64 {
            get {
                return ((string)(this["Image32Base64"]));
            }
            set {
                this["Image32Base64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAIAAAABc2X6AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8Y" +
            "QUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAB8WSURBVHhezXvZjyRHfl5k1n1l3XdVn9Nzz3DIWVKkbe1BH" +
            "fBagI4HQ34S9CQ/GfCfsPsvCNCDAEkvhg0Y0oMEyQIsWdKuKC7FPXjMcK6evqq7uqrrzsrKOvPy94uoL" +
            "vb09DR7uENqP8TEZOUZX/zuyGzpe9/7HvtaIEkSelmW0du2bRjGbDYbcUynU9M0HcfxcOAccTJ6bLtcL" +
            "rfbjR5bdIAfcub/TsNxaDd6nEWNn4RLcDlAG9/+9rfFqV81wAcAVcuyBFtgOp1MJlO+aZiWbfPx4hxs4" +
            "zSL9/iJA3QhvxYwTd6wcdwWwCmOg7kzHf4T88j/Fzehy79CCQtRzAXi0ADAE8IExZMYj2f94aymWkdDx" +
            "rzulN/t5nKUSUQShILfXrfLzQUsYzekxsUogLtjj0tmbhlXs6CPhf3M42KGxaYGnSkzB5fRtTJJ+CsnL" +
            "AC2EOJ4PO73+91utyegqhCvYTha34aa88G7eCMW8ysJ2IYhiJ1kESdwTDzEkjGWjbJ80knHmdfDBkPW6" +
            "rG+zkZjZ2pgnmRMHE58ZYRP0gMWKmQYJvSXy3amD8fNdm+z0qxuHjF2MD+VsW/dZdfWWTLO3O75nlMQt" +
            "+Yyp0Z7JP5Tnv/EtstFlwd8LBCgPf0Ba7RZtc7uP2Y/eUR7BH5ewgueYkP0UGAYz2Q6HY9G/b4GWQ7Ad" +
            "WL0BtPNz3QMhjGVMWxwSOy//x77D3dZKUeSoR3C1ZzQWpIvpwqXhwfQhtjmP3EievwkxXYxj4eZJutpr" +
            "N5iWxX2zz9m/+tv53cCfl7C4Dbf4tscEK8FRwT3q2lao9HcAba3wCWdYLkMUyJETJJdfh+8r5xNSW/ed" +
            "O7etAsZ55iwdOKu+OlIzJZkh0hiG8z5Tll2QPhz0FTPMZuydo9Vj9jmHvvhj11/8hc+xiLFks8D9/AlC" +
            "C+kCqUFP6G6EKnwvZDkaDzVhtO2Oq609ebDFmObjE1X8+yt19ida2ylxMJBCAQhhzwJSCZge2lbiTiwM" +
            "hIX2ODuXHDEjYEk8WR8N9+FsCM2eFvAZtaElLmjslqT7R2y7X32yePAj56UysXCciGGmPflJSx4CqrgC" +
            "X8LkQ4GerfXrze7O82B3Z1hrhkbMza6e9NaK7tuX5bfuu1cXrGVMAhzWfHJc8mOxz3fc0K0BEGHn8m3B" +
            "J7fxmUOm81YW+U8D9jmLrv/hG0dBC25kEznS8VSKpXwer0vQZgGR8rmiOhyHEsNiHY6Mwb6+Kit9/qaz" +
            "2qlgtswyGKWxRSyKLgTarI7nZCurTurJScchDbyMWK4/H+hwyc1GcBPseckYeyxbWYfn2lZzEQEmrHJl" +
            "OlD1uiwpxXS5CeV1P39jOGKX12KZlOxeDweDocvJGEuAwLUD4A8B4MBQosGdzQYDIdDUJ7O7HtVTO8E8" +
            "nz7Tv8bN/q3NtiVNTJaYZYzA3ECOixlkiyTdHzez5kRpRNxdbGF/SBjIVpxhyQ4YyfoGQYzTNqPo+Cp6" +
            "VKv7xxxnwy7rTdYS2Wm53YgUorFE8lENBwKgiocBknsIhImRwQQdQky7XY71cPDWq2+u7ff6zT5KSyjs" +
            "FKBrS+xSytsvcw20C+xFA+JuBoSgGlhlMEAi4TIlxJNflfRnwLmGDK0TGaCMJIHQRgWDr01mD6SxhNpO" +
            "nPQNJ38Eyz2s6fsT//K7czgx7y5pfLNK8uFfDYej0GwPh+cFrEAziZMM8EFK9ySsFWS5NTUh6NWu71bO" +
            "Xz4aZUxtDn+4D+zt++wcp4cEiJhLMLiCgsFmYuHVsciUUA4sFUoOfwt7VwIc/7/58BxHBWqiw0KuTzSA" +
            "sOJ3O27W12p0bZrDaPdpQjU6rB7T9hHjxOMLd15Owf/lIwrSiQUCPhht5CtYEt3fhFh9AuqwlxHo3Ff0" +
            "3uq1my1n+7VRt0aY1yxGPuP32S//S775ptsqUCUoGm4nmTCkz4xUDwOTez8Ygjh800Bugr3cdhw6Kq1f" +
            "HuH0r0n5g8+mP7ND1nUzRJpZsuxULS4tLxcKhVj0ajXi6DHc8lnn3eaMA4LniB57JZmyP+Q4dvGSLL61" +
            "kzVtM5Qr4YDJkwUNhlDUElRqnRjg8UxxdApi0cIay4cKCSfAP4AkHheoOdAXHU8ZsuQWj3X1r774bb04" +
            "aeTP/sL7Msxlrh8K5ZPh5PxSDIOs00EAgFRG+EwFy2B3+BZwnw6JLAVOQOcE3r81+4b46m5npmuF0eR4" +
            "Gg80WczDb5npcDyGYbcNREjHVZCzAtjwVM4q+NHHItU9C/FVgDzhQaTnsnaUNqvsx/fY+/9TPrgY3OrI" +
            "rH07V95fTmfTSgKfFMA5ipqSf5QEp4Afoj+GcLiGESqqmq73W40W5X9w/29rVyMra+yW5fJ8cIy4XtMS" +
            "0pEpULWySQcZO3RMHPDGx8r7VcB+CpNl5s9+eme848f2H/4P/AYODT/m2++trKynEwmI5Gw3+8HVcECw" +
            "FVCyM/0grD4Aaq6rouo02q1dvab9YODYmzyK98idV0tsXKORSPECuqKGI5wGgqQ4/V6uRC4R32VoEGx6" +
            "ZRKn25fJE/Sk13pHz6QfnJf1BmKUipcW8km49FwOAjCXo8L6Rr36gTwh8CB02EJARY9qB4dHdVqNbBtN" +
            "ptHRw088+4N1+/8uvz6dddK0cqnDCVkY3JAGKMRzlO0rwTcSw0GFF13q+zBFvvRx+xv/kU2Jzjg583HF" +
            "G8i7A0HvVDnoN8XCqKHY/ZAqZG6Ygpgz0AwSNMB/vMVD0EY6SF4ViqVx48fw3j5M52lvOe1a56VopxNs" +
            "lTMcoccycdcyJ8QXdxMclF4JFG8qAEnt18KNCiScE+T2irikFRrSQG//PpV1+s3XLevum9fla+XZ+VkP" +
            "6P0UmFN8euSjfR2gjQe9dlkMkZGCLWFVxJyxt1OE4bpHhwcoKCjR3EUMp5r63IujTzRVkKWC0kShg7VP" +
            "UnmHM6LQ4tLLg5+lWFK06lkWlRrxKOu9bLr0rK0XGClvFPMWPm0kU1OsykDG5nkLOiddfvTD++P6g2Q1" +
            "7W+2um0EW7gzAAY9jOEMR+UKs5mYj7GY4RZTzYpLxedmOIE/abfa/kwCIOZM2ajGcw2z27OYtuS0ByLa" +
            "/3LujR+smUjcNCqj98nRyNyJsGyKcpP0wkrFZ8lY0Yihg0rm0SYNELBseToHqaN9X69ofZ6arfbQ9DJ5" +
            "/ORSORzlcbthGfDHqg7jmE+JpZ7PNQdYxJVaFmMFsIsNhyT/0B+gxKs06dtVaO0Eb3Kt9UB0wasr0vaU" +
            "B7wNpq44NWRSCOjlFzIRbjYTzYQe9FEcH2COJAdwkcmok4qTqEhFXOScTuFFrPTCTubdFCrFNJUaaIUQ" +
            "w/n2m4yHdk919zr16/Dk5MZC8Kgih5swRMmLtZK/ejcbn04PDyykL5NJpQSYwPe8uCIHTZpo95izS5r9" +
            "lCmSEdtas2u3Oq62qqro7p6mquruTUdhGU4TxBGJfi5kBcuHRuinQW4RmRvAb8TCTpwmbGIHQ2jwERz0" +
            "BARwQ3BEtERxRksXJI9DvOMJs5h08HYgI2NjZWVlUQiAcKnMy0A9RAUG04LIQrKMB6PVd0wLWspZa0VT" +
            "JixbUPrDQRsKLckzdwuahIzSAGQ4fGkFw0+Ag2ppc9Lo8mlaFioHAI+XjzwCgmpMujjNJ9XAiucjKp4P" +
            "o6TECog2vNY7DQl5Nibu64HW84nj8y/f49tVfNXbxQureZLJdTDqbPrYUhbpJZgThtU32PTdDHT6zJki" +
            "tbTyXSMjNOcjU1z4thj5oxsa2xbU8eZCs4io5Shw3ADHuIJtkhFoXiihKJiyMbk4rgTj0r5tBRTpIDPc" +
            "btscvunWC8oLTYWJwijwK2Qh+lSpe789J79/kfsp5+yB7vs6o037ty6mk4nQ6EQlBdqewZhACYtNkD+x" +
            "AoO6l5a3OBry+BMQI4Nz49GOkCg5XKYO5ph2hPD0sY2m9psTMK/c8t+57a5WjT8XtxsbJjGaOxgXjaWp" +
            "VtX5GJGCgVsr+cswueAjxQVck+TYVCbe/YPPnT+6H8iRHvW1nPXr11ZXV1DkQhrFWb7QsKnOAOCg1jKF" +
            "8IXbwa4MxMvDeiWYp3LskWlxcmbtmE5M9Pxe6xibBYPTxwLWXpLGxxu7plQ+N/9LvvVd1xrZaRu9tkSP" +
            "hM4DWO0pKkh9QfOfs15tM0ebrMPPmI//Gn+6p2N25fzSZT/0Si8EuhgmLjobMLPQ0wP36DumY35PwE6k" +
            "RhjlmgmTgCzAOuYjqeTIXL1w1rt3oOnlgFHwL7339hvvkvRNeiHObwMYch2Kqm6DN/56WPr7/6F/eX/o" +
            "+WBW7dfu3H9WrFYDAYDpMYnguHcS38hxGUAf2dB4DUJAf/zRHUBpK+UwWInvD2yPF6CIxwhhbDUwazWH" +
            "rV7ujXVri6p37hh/ca3pdeuSEjUUW/Bb9Ey3ufDewFwAs6z4U6knuZUG87WvnPvMfvzvw+o/dUrt69eW" +
            "S9nsxlFUchL8Yg7v/DihJ8H7nISJ/eIEwA+QQQIeDyeIFevHXW39+thqXZ9Vb17Y/LNt+x/97rr6ho8m" +
            "QOPRS76Imx5jj2Zyl0N1SIcMvvgY/bRA9bSsxvXVu/cWC0UckglMOnzS07gyxM+hTnXE2wFsAfmPp5Mq" +
            "bTu98xxIxt4emPl6ObGGDyvrslrJQl+2+91ZNcF2AI4h6/I9vrOYYPWKFFR/PH/TlVq5dduF9ZX8rlcN" +
            "hpVoFzz85/FKyO8AFd8erGLIgpeSx+O2h21Wu8+3GmPBu21TOuN67U719jNDVrrQ5KI/Aljg97Rxaen6" +
            "wTAEwKDbCnbkzo9Wn/+7Cn7bJPde5qpTEu/9I3ly+vldIoiEGSLITw/+wA3/K8A3LPTG0Nks5XK/s/uP" +
            "7n3wWPX7NGl8t7ty/KtK+zaGgpsJ66QWyZzxNjOYbsALYBKHVXaq9Gq3T/8iP3VP6V749yvv5G9sZEv5" +
            "HOxWByyBVU8fn7Js3hlhIVcATyJgux4ovb7vV5nOmxFXPW317Z//3e2vvvvezcvmaslO5dCGSDJFCx5d" +
            "fkiQKrzRhXIdCT1uqiNnZ0Dm5ba9/wfPV3ZGq1ncisw2lhUQeYokuL55WfhomHpfMy5ci1C1olkva9pz" +
            "XZrNmrFA91cvFtItwtZo5BGsclQ7oQC/M2oGNjZkuDACWSx8MjyeMKaHbC1Dups54DtHrJaZ7U/K0bju" +
            "XIhE43S4jO8I8aA685UZoFXQ3jhpJGQjMdTfajrWmeoboc9H6+X6O0ZeGbTciomQ4eRXZApXmw9CBko0" +
            "s8Jgu1A2ju0HjylJR7IdrdZiCcLxVwGNRCqAsRbOvkFanwSX56wECk2wBPOifzwYNjXho3uaKAPC5Hue" +
            "nZ3tVBfX6IXv4ixGBIKWj+yZRQzuO5FhEmBuXOyaZlSRzWq2ijLqkdsr8q29iHY8oSteALJRDwaj0VC4" +
            "Brwiwj0dRAGWzwGzknta4eHR3sH9Xsf9ZhH/73f0N65M7yyCoslV4wKCVqAhik6kfa8ANBkNIuWKVsde" +
            "adq/esnzj/9K3vwmClRllt6q7y0lkgkg7weQNozv+pieDnCQqQCPFWGH6Y1epSQI13V1Sqbbfk9DTBEj" +
            "L1+iZXzUjYhhRWbIgpfnT/bGwupAg6cE32PYhiOPqR3n4i0T3bZ370f+D8/SDOWuPWN+Go5XcilowoZr" +
            "Qg/mPFzjPYUXoIwlyiNSzwDpRIyp742aHb6PVWNetVyqlvKNAqZCSw2n6YGTfb7qEgkiQl1O5OtECkOW" +
            "TI3V3bUgho71TotVu5Ak6uljlm6ulYqF1KRSMiHfNUjVttpPBdnC7wEYXFfMZ2Qra4P251ur9se6/WA/" +
            "Gi1MLu0QgvX+YyUSch8kcX2+ESZL25wNsRo0RsmYqw8GKHKc7YqzuNd+cmu67OtSE1PrReTkGoun4eDQ" +
            "nrMryO8FFWB8wiTQOc6DEN1UBCjBkYlPCI/PKl39PeeqAVP51dfO7p5qbFSILbJOH976IdzomyRIVs8k" +
            "7CQKg45EpzwaMxQ30GwqsY6fanRdiDYSr3Q0vOmnAqFlXQiElVC4TC9W0CYBc8F5je8ML6AMHpxX4h0M" +
            "h5rgwG0t9XuHdY7Tx/1GBu9fmP8u9+dvHHDXMrb2SSL0McbJC5cOp+rM4FDaBRy5OFYbneRJ9qIruh3q" +
            "zLqAVWTfKH1XGEtlUZiHA2FYLFekVFgVAuei42L4zThY5GS6oIkX+igtR70yIo73b6q9qxJMyg/Scesb" +
            "JqtLZF/Wi2zdFyORRxJ6DD8E0lP3OlZcJ6WRe+KRhPyw92+hGr2acV5tMV+9kD+6CH8G06C3RfuvrO0X" +
            "EzHopFgMAizFWPjq5/gDhOeV6yAuDfwhVPwDOH51dwngS18L5U4mjYcDkejYas3+vRwVPQP76z2Ly+3w" +
            "PPyCqMF+gipsd8rud30oR/hRWwBrsmjEaVN4IkCYGtf2j0gb/y0Iu8e+hiDiYoqIciS0Y1iJBr2B/w+v" +
            "588lc/rCQV94aA/EIDnwg4P8ea1OukhZ3s+59MSxtmCLUKrruviJVO11tjd3pPYDJHm2jqJ9NKydGlJX" +
            "iuT0Xo9PNpgls91TnOAiMM0jR3Upe0D9ulj9n/fd97/GQ5IK0W3H6GGMkQEG/LAGDkNnkTg8nj8gWAkG" +
            "Iqg9wUwB8GAn05HZBKcBW260Xm2dExYnAS9hVQXEK8Rm6329ladMf0//TL7pTtsfZmVsiyXZHF6Syr5U" +
            "ADgUjGpFyHMJTwcSY2OdNigPPHeU1rTjwSlgI+0VZL4CysmO3CT/JMoyzZ5aAi6XFEmR0azcHsQGhl+M" +
            "A4HIWSwdUHaUHuu+d5FuDoTc8KYHtx0NBp1Oh1IFT3Q6/VQBugj0zJARfqv/4V9523p8opTSBsJxfCI6" +
            "HCe+pwFPpLZjN5L9DS51pSqDQmFASyUL1ZLSJ5xTygMOFoWODs2Gn3vgStl03K3e+5HO56fPHb3J55Mh" +
            "Awb7JBRl8vlTCYjlmNFpnmmbs8XABY6DAU+PDzc29urVCowXWQXjm1wuQRuXfHlMx4l7EKtg5DjouhAW" +
            "keziePoL9K4kUP54HE8tP5Ob0bScXpXlIo7yZiTjtmpuAWPmEafMNEyCSuTtLJJK5cys8lZLDIJBYbx0" +
            "MBj9T95CBUkQFRw5ghaoArDFoTPhOs73/kOBg62oAeR1uv17e1t0J4fR8XqDdgWWPriYc9s5p7MoAsSC" +
            "nbTwqzzobsY1JCYXKRxzqiBMSTMWjhIawDJmJ1Q7HiU+kTUSUaxx0nE6AVSKk7TIT4mQeqGyBePsnCYh" +
            "UOUwKn8/RYA9YzF6MtCqLSoiiH3syX87rvv4mwQxiT1+30Q3t3dFccwT7gYHjIQ9CohV2cg7dTpu01aO" +
            "mYwLxv6Bq2DAtLrEZteJlqLl4YvasbxO0fMGX2A5XjcDkoov/9kY2gBtMC8odIKIhCEWSDI4NNMyzede" +
            "dWBjNCNtAxDjUQiKBKRmUClYcnnERYqzb2CA4uFATcaDXEMO+HGsHMyRoFLX7j0e4PhSPe6xvQtcN9qd" +
            "51un2LMeEqfYrd71Oitooqajr9b5BvU+HtGbKAewDktnNabv3nUR/wDCjeTPVwFgJMmwDWCGhwZP8GeS" +
            "e2eVG9bB7XZwydOS6UrFEVZXV3N5/NQbO7ncfbZkL7//e+DGABzhaPa3Nx877335gc5uFfAY4k/eowsG" +
            "aXPdpA8YuKXCrQcV87T6yLkEib/cEv4yMX0Llwm7B3+x4Iu8GUseCncJBqhgnmlyKJRTg9Jy/PAfjQYj" +
            "sP6Xemzp/KnT5xPHtn/+CO2zb+Nu8VRLBYDAVp559ecjbmXhngRARCHIF7QhmBxmVAJznauHVADUBpOm" +
            "TZhHfSGfTfn3N1gS1kH0XgytQzT4fND6SVRg9abE9Pir9rskSyNfV7b66VvJpFCB/1kmSitMF/LBUdRT" +
            "hDGxnHvUFom4c4YA55+1KbFynubbHMv9vQg2RkrxUwkl01CvNBq2DDOmw/3LHyeeECA4Az9BVs4bXEZI" +
            "I4ugB08SDCL3qaQrw4HnBAyStgmclDL5hmAjIMUQ6dTeP6+1kc3HqtKsLNeNnMpGXZrmBL88/oSfbwAF" +
            "51QyHqJIUXA48YV05rQMmWv7+gj+rKy3qQK+fEu6+iXHHcBlUU6nVD4N0tgu5DTi3A60wJwAdfxL6iqa" +
            "TLoTEgSoqTXZyZ/uYZrsN+kV41T1Bswfn2gTkaqZPdK6dbNDWO5QB+Fw8mHgmArQZ+jYfgtmzJTui91x" +
            "y6NNuAdkHgiYje7UqvrrjV9B41AQ015A9lYPBWPJ+LxmNBkjJkuPhfPEObaSGr0hWwBcQInTG968QuaC" +
            "tVACYnUW9NH7d5gOh5EPHoqosdCelwZ5NP9tbJZzEgIvyDsdpGQI2HEJ+ZxI8TNRerMJH0kDcf2dMaQk" +
            "8DJVQ6RitJ3BtqwNDLzjjvj8ir+QAjZJagCIvC+NOGXwokZoTnCRGGyoMaaNuh0u3AEzfZRSK5ulLWVg" +
            "pxNGsk4fYlRylEPwvM5WnzsJRwNJzwZIvGUGx2no9pw5hDvVoU+ch/NisFwPpEuZjK5iKIg6JL5HKfQF" +
            "8QXE37+doLq8X7qSYfpQwFjOBq3u/12u+Nx2snQfjlzuFbiq5YKVVRKWEZGEY44wt/O/Th6i9ZiDYRx2" +
            "4Gr7/XpG5LqEX3e3urG6p1ktaN0x4rfH0zEwqlELJWMhUNIrcUHlfR0MaSL4MtLGIQFZzwLmqwN9PpRu" +
            "1pvv7+psvrgt39NfedO5/LyEPEGlQYCGM7FCL0eh7QP8hTTJQSL1FqX+7rTH9iI1Sgb+WIAvdSfWuuSt" +
            "xhUsoFg1IfqCH7J66GKgSokcYu5AC6IL09YAGYj8nBV7VUP9uoHj5CMr5TYt96kv2GBEy5mGLJFyhlgX" +
            "0KqfHgYJBpmAXaH3KOtSs2OfNRyDo7kSs27WQk9OVRsOZpLxbLZdC6TVpQwuIpK6KVEegovTVgIFhA8J" +
            "5PpQB9qg7457rqsquJ/gLQkn2EoldeXkPqSW6KlPBjnyREa9DIBDmk8tcEWUq3xj6COWlBjf2+0MZUKz" +
            "IOcyR8K+EKhQARVv9+Lwlc8+iI+9UX4MhKGn0A/Rb2hD5FwNpsNtVvJRatrxWE5Z+UzdjYFL+Ugukbor" +
            "1c4VaF96LkOGxNJ1WRkoM2uU2/Z8MDklvZZV/O7vaV0bi1XKEejMWgwV90LVfYXxEUJi4dhXjG73D/N4" +
            "J966gAB1mPX4oGfrhTYpSX6wzNUM9GwHA1DtjYTf71i0ZeIyDRMk/JKOCdtSEs8yJnEN277R6mtWmpPV" +
            "SLBUCEVzmUSuUwyEg6hzhOTy1WYQHf7+XAhwqRGx5YDqiiqEHUabXWvPihEtDeutK+t1sF2tUQfoCGpQ" +
            "K2Lnj6IgyZjopCZQaQDNKRK8Eys2Wb7NbZfp7+H7GpQ8GsBZTkUQblDxQ7qM5+PalrBVuCVsAUuKmE8D" +
            "7IVa0BHjWZlb69yUJ2Na996w/rlN9mtK8j+pULGCYQ4Q5NqAxFpacwOfeF9RCKFZ0JuKO/XvA93gu89C" +
            "gxVz/JyeKWcLxWziXgMlR0yRCgxyL0qhqdwHuGFYIV/AlVN01S1X6m2dioHV3J719epVLpznf5KKR2X/" +
            "CEeYFEsU6qE6s8ZjmjQGDmkSqG1QSKlD1MHl/tGzpCjyJWUsD8SDkTCJNlX4ofPxxcTBltUjqgBer1et" +
            "Vrd3tmrHrRhl7/17vSt15zrl9iNS6h1mDfIr7GYZcqjidzqst2qU2viatoNPwy3tFnBLEiSqxxPrWRyh" +
            "Wg0DpGSZ5r/Ufgr80zn4OyPWvjT51SHQ7jigaqqrVZrZ2dnf78CL8tY7MbleCGbSMajyag3FKAsaTxif" +
            "Q2pLzneSs1+suNs7kKTY51+ttYpVdprzfEG828oiWIimUYpF+FipUyCm6t46HwEXxnOljD0Cj10WCyRg" +
            "S0AR3V4eIj6kbHC+kbixiXf+pJrrWhtlAeF9JFL0mCoqkbut0bFDfVwSL7gekTJeP1Jtz/u9sLxAuKbN" +
            "bfg+VV4pnNwtoTxYMQeqHGj0djf39/b23v48CFUGjsjGH4uHlVIFZnsRqkkOQb0oNmdwPFu7Xk+ehT66" +
            "3+O/u0P4g9rKeZdln1ZTyAdiiRjqONiUSUSQhoMN3zKCX9tOC1hKBU0eUR/CTwQi5ggXKlAjefgf/cVg" +
            "elFQi5UdgnFLCS6sXCHClf6HD7c6C8fjVIefzgbDyjhAI8xPvqTE9CkPzaZr5Jzr0QQt/3a8AxhsiFJg" +
            "t3CXA8ODsC23W4fHR1BsFBEGJtYHxOfz8JBuV2m1z0LeM2AF9cyy/EFleVUuhxLpFG+IaYiN+SpkrgxY" +
            "f6kfzucQRhWCm98//79jz/+eH7gGNBDnGAaBuQiyT5/MOoNRCxPyO0LxvjCdTIaSiWVeDSCBGKxPgzMp" +
            "fm1y/N5nCaMHr4Kavzhhx9ub2+L/Wcil8tnstlYLB5RoqFQBLrr93v5Kz1ySBAsl+3X6pAugjNsGBKGN" +
            "4aXEoQxbtELkJPlC/TKMSIRyDMk5CmWWgR+QRiewhmEkT+KbBl+C/YMA8ZOMAFASbAS2xCngNiP6RA6A" +
            "gi2v4CczyAscmZQhaiRdSCpxE5BCU4L9MAW3HgEfSZbWGz8IuOMSIhxgxIFEw4hQ2D++wTELCzIz6//R" +
            "QZj/x8KvdFVnIc0qgAAAABJRU5ErkJggg==")]
        public string Image80Base64 {
            get {
                return ((string)(this["Image80Base64"]));
            }
            set {
                this["Image80Base64"] = value;
            }
        }
    }
}
