//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickRecordEditor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class SettingsVariables : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsVariables defaultInstance = ((SettingsVariables)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsVariables())));
        
        public static SettingsVariables Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Image32Base64 {
            get {
                return ((string)(this["Image32Base64"]));
            }
            set {
                this["Image32Base64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAIAAAABc2X6AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8Y" +
            "QUAAAAJcEhZcwAADsMAAA7DAcdvqGQAADfbSURBVHheVbsHgCRXeS56KofOcbonz+zO7myQViuhgBBCA" +
            "UkEIWRLAhkJm0vmChGMLxdsY4wf+Bl4tuGCgYuMbQQ2mCSQjUAICWUUUdjd2d3ZyTPdM51T5fi+Uz3S9" +
            "a2p6ak6derU/58/fd+pHubdf/v1ZFKp13rZtJrNJFY2GpzAT02ObFWapuXO7x9vtga15uDQXFnTzM2N1" +
            "tx0XpbE0yvVbDpWLuWW1ndszzuwb6rZ6FUq9fl9o7IkLCzX4nF1dmZ0c6vRanUO7il7friy1RnNx1SJX" +
            "9lsTU+OCIJwemmrmEuMjOSW1+um7RzcX+539NW1xtyeAs8ziys7xXy6kE8vr9X9IJiZLLXag0ZHS8ksy" +
            "zD5co4JyfLyOjpgX99q6Za3d6rUGxhbO609UwWGBCsr9UxSzucS1W00O2Nj6V7PYN7/91+zDGdqvNjua" +
            "82OMTs94ng+1N4/O6qq0osnNibHc4VCamFhIxWXcLy8Ugt8sm/fWKPZqW435/ZOMBx7bLE6U06VComll" +
            "W3bCaC/ZjkLZyr7pvPplHp6eVtk+dmpUq3VMQ13brq0utkwbW9uT6nX11e3WvumS5IkHF/aLqSVUjEJ6" +
            "T3HhfTNbr/a6O2fGXOD4NTy9sxEMZ5U9LbG81y10Rd5ZmYq0+4Y1Xp/ZryIxpPL1WIWZsguLW1hjmYni" +
            "90e9O+MjWIG+c2tuu973EVvup5lWYHDfDEczws8RzCDLCeLHCEhG4aKxLMMFwSBKOACcd1AEDhJ4D3PJ" +
            "UGgKAJuDAKiSLgaOnYIB5FE3nU9hoSqwhMfjZ4k8bC86wc8xyiiaBgOwxJVkWwHggUxRSKEWJaryLibt" +
            "yxH4FhVEm3XC0JcFUPCYpCYKnIs4zouOpMwFHlWFFnX8QnDiBIXhGEYMBLtQnAfhOR5Fgccx/Ec6/u+b" +
            "duKCFUFsTCSX92qo3VmaqRSa/d7+sG5qe7AXNvYObRvggTkueObc7OleCL23PGtUjGDKVw4vSWJ4t49k" +
            "6c32uuV1tkHpzE5v312qTRSmJ2eOL643m53zz40a5jB8wvb0+PlsZH80notllBGStnjp7fzxdTkRH7hT" +
            "NUPwkMHpjpdY32jceTAaEIRT52ujhczU2P546fWGSY8uG9svVpvtnvnnr3X9/zFxU0o7NjmeDmXL2RfP" +
            "L0ZhuTg3Hinb6xs1efnxlVFff7ExuhoYXy8eHKlZjn+7NSobVu1ektVhGxaYW7/+ndgirjC2TYMQBB7m" +
            "AzDcjDrHMfqmqnIMi+yumHzLKfIvKbZJAxUmbMdZ1SxDhZOVLXs8515VYBfEMfxwpBRY4ofBoZhKpgVT" +
            "LPlaZq+sriWScvwoM2tfrkUh0+tb3XS2Xg2E6/tdHDj5ERW161mQyuVUiwJV9ebxWIqnYmvbOzwvDQ5V" +
            "oDzJLM5BKfnOoossRzP8iE8znF9UYa0nGXaIs/hiQPDhN8JcDS4kOvD9HC/uCIalssTImi6NjFWqu20O" +
            "r3B5PiIadqrm9Wz5mch9+Jabd+0Uiwkn/zdxkguViyka7WtIPTGS4Xl1a7Knbny8FePVd/2ry/kXrG3W" +
            "BrJL5xetx1vemairxsnVipH900UsokTC5vb241nfv3byslNQlYJyRGiwSkJSUWfOiEx6qWkR4hCiExIN" +
            "/osEJIhxCeEifbW9bfdNDY9aeqG6zDaYICwn5ou15v95Urj8L4Z5MPnK7XxYrpYzG4f7wQknNs71m73t" +
            "xrdfCahyCIiyHB85qPf/DdZFms79VIxlUjEVtdriipNTZbXNuu6bpw9v6fR6GxsN885NIXAO7W0c2CuL" +
            "PAEMzIR444Wd64+/BenWh/8ee3Gbqu+ubUzv29cRJZerCQTytyeqc1qs1rrhIY+aLV+9sOHLjtcfMcfX" +
            "ZuIS4hbhqEeAadlcMSyUDcIEM8+gpOEDsu6vmme/tI9vSeM7+fYDYYhzeD6D1x69NVH4TWI8FqtYxh2z" +
            "yHI86OldGW7penmgbkJpOONanPPRJ7jmDOryNJKIZeE1/Q1IyS+Kkt86LsiJyfiCubQdRxMgxglFcjN8" +
            "zHDtCAUvM5x4OlBPhtHoguDIBOXyjEtxlmhh9sCpBmOYfPZNER2bCeTVEVJ1DUdnplU+NMvrBx75DjZf" +
            "iZz6S1vfvOl6XgisiceGEQW/q/Hwx1WDUnQO/njR3eeMB5uhRuMRZBLQ18QePgqniIpckb2XqWc1tmxu" +
            "hNDio7FFMOkYYlc4/qe54XJGJ0beDXPI0HCkV2OJaxlWr5rzU0VHdvdqjamx7LpuPT86Y1cOjY1PvLcy" +
            "fWQCffvLS+ttzXdPjg30ukOGvXu3nJqXN2MMWs0JfqD48sV5PCz9k2ikO5stw7sQd5JPn9iNSaGB2dzI" +
            "u/X1s1v3fnlj33kenQLg57TfcDr3+v3f+Vrv/IH9/mD6HjwSxwEaOnc13zqkZW7n3p6x3x2Om7dcIRcd" +
            "w51eCZUFKWvu6tb3XQydnhGvvHCb10w+tjxM9VkXJooZ0+t1aHxvtnRZlur1ftz4zmRZU6vbCP1jI6kY" +
            "UDMF/Pxb/6L6/pRiuI4gUURZlkeBcr1PDgbcgAyO3xNkQU4m2MaBon5DKeS3vv3/XteeUZWd051bvve+" +
            "g2BbyH4cwkiiexAs1EjVFW2LKvX6T3y84dXn1l7/oWvI7XCcL617a2ej/LHoAIKkXWHdo0OGIF4Oln74" +
            "tT2HYX3Ef7k0fzoNZdCgp0v/OvVt152/hWvTCZjCIC+bu9L1m4550Mrzfd+b/VaFzqEocTznu9Dcllke" +
            "IZ4NrIwhg2j4sTLIq/pFosq53lBp6+hoqYT6kC3EWCjuSR8eNDXR/JJ2BCVPZtCpJNGvTFf0M8qDsrMp" +
            "iy2RIUPpQOJVPjKaeNgpjbNnijIjioJvYHuem4urXZrjd8++Fx1sx0KDOQYuivDq0zun8P0/yLpL4bxD" +
            "xDkTWjAUH2xGQujvSfmTrTKz5C0eN2h5OGpIEECCU7O+l5gGZYisKguxBm4es134ejqSA6hRLoDO5+OQ" +
            "eftWjcdQ5DK1bZGWG4kn3F90tFMZCgOidu2vXIhhZq+0xo02tpUOWe5/qm16mg+zXKJU0uVQiZ19NDY2" +
            "kYdFp6fTt5w6I4YWQgmmhLqD3tpMHJliamMGH9D9Cqzb+WnT3zoyc7++b1zDsVG1VPHzjzxoycJMZGKI" +
            "8AQBiRg+LhYvDIMjTDsEytG0OxxJPSpmT3i35+x/iZ3n8L9wzg/Mz4jpnm3wHs9dNpBopmeGOnqdn/Qu" +
            "XimXhA6iEnb0hZWd0rZeCYVO7NZycTj5x+e3qzW4ZWH5kaRyZbWt0uFHPwZKDCTUgGiWBYJh+ITZEuGh" +
            "2MDqtLZRvBSkyDdiUgVfojKKUmxZndfu39x17q10r6x2p4K9AYz2A7624Nuebv9ZpMpSLJEhyIAPajcN" +
            "P1+/Vu3/faZb+QLakCVoxsScUj4kMkEYYlQw6OIRB7tk4rJrmY47bXz5PVz5LqafEnDPbM+u9J81/+4b" +
            "c/8XkCugMoZzhTak4UG5AxDDuGD4gyxke1pbRYACTmWhuiwDfUAmZfhBUQqw8bj8ka9u7jeyOfis1OFM" +
            "5vbumGeNTdR7+qr262zDkzbrgvsUsilxkYykpq+46nXfOnpm7+9eetX1m69b+2CYOP7/vIjlTPX3Hv85" +
            "r945CYtd8mevfsWVyu1envvRGkkg4RsnHPW/ovOOyedlBHALykMETiGkUgo0TyPmR1qHXINy9/qsK3cK" +
            "JkcFQ/rsSmn/8hC4UzrVZdfUJqcOL7aJaKSL40VC1ahUMONgpKbnZzc6VkL641906OCJDx3en1qojAzW" +
            "Th2ugI8c3DfRE/TVjaqB/eOc7zAXX7DTUjeKlAmPMvzJEBNUbBtBwAUaMZGEgiQ0vhETAau1UwnERNlW" +
            "QB2QeSPioND2Xv6wdXPWle3wrQSU33XtSw7lRBtXT/53MnFE8sbi5W3/+GV05NFOHOUl2AV7Hxo1pju/" +
            "azzLPGfoA4VkMrv9m4+MPPYk/Lzgrr1/gR/ocZUVHsp1Xt4ZzwpT+ybzWeMI9PN/enOVGJ7JLUBOI+0T" +
            "cR4nA/2xCqH8rXuQDI9IZFQIRywtyIiLwOEO3giUAoERqizSIClfDydkLp9A/yrlEuoIrtabWTjcimXW" +
            "trpE5Yp5hOSLBgBWWtriZSaScgC47G+y4YOwxhaUHjBGzOlRDGvdnr9ZrNVyiVFxr3jc1955D9OEIKk6" +
            "ER2HWYlCixomnI7pHs7Y/49S0QGJMUn3QW18pfxhx/l/yHld+e6if29zsn01lMKqXtgEa2+daBw6rpDn" +
            "37N1O3nlf9YFVuEz4TJPdnsE68of/jS6U9dPv1ZsXuG+N70WK7T1Tqd3uxYKiYziOe4KpbziWqtjRrKf" +
            "P6HP4S5YrLkAZsjyJyAEzhQDcMKysrggtLvJN6ldEPgfBbR4ktyemmnfM9CNhWPl2PujHCm68QXzJGYz" +
            "AHHYMo0TXNMc2tt6/v/39f/7qt/ce0bLshnY5lUAhjqJZ2xyUR7nqm/HrGOLN17dsZ4IHvfce6eR9jTr" +
            "zt7YUqa+aDFjpCVPzWm1qRLjs6Vy/nJ2am8tJVjT8WTI5LMzqQejYfrxKvtaOef6ZzNszLDcIu9mbYXt" +
            "31X5onAAg65CBxRkgzLCoMQZcl0XEoMTUrHmFRcScTVgeGBrEMbQGJi78yPfHlv7msz6a9MZR6cLTy3p" +
            "3R8PPebgrLh2RZSg84lfzc4sGSWTK2L+kqnRcCkkLWt2kalDvQ7PlaYm5mAtuBu/0Vb2LhFgtrLZ2aFN" +
            "f4Xv/OY8IMRqTKRSMylQ071dck5s5msdyamRssTI5mMvK6N/mTpFY+1Lnq6c4HZ40jrGbK92diavWvz4" +
            "ofb5z81eEWYHBNlpdbUgbES8Virazp+mEjGXI8MDDseAwlluCtvuimPZM2yQDAgE+VCEomt1u6NFVNir" +
            "PD82gVd5xovuEgxj3PGGaL34MJxu3VB8kVJ3WuwiW4fACgAAQQtaTR7uWzatd1Hfv7QyvFNs7P2+ze++" +
            "dDBKeQqiphptYXaHHGtsPFV1vo542/SbM6TzVPZpXvU46+94LfnnjV2qyYe7Xm/NMy7etpact/s2KWvP" +
            "pRKwyE78Mw9o0lUGlNrnZt6kvX0h+ufXBGOjBRSrmlZphb4Ds+F48Vks6N3B9Z4OYNKs13r5JJyNqlU6" +
            "j1V5pHA4cJUFCQnsG3QdHBoL2RlSeKk5GlzctOa3DHH++bcYHCe3i+HxqpEqplYD/Ml4XYWhUygFJLjX" +
            "OBscFXL2DhVi4Honn+9qgJJYcP4uwFMiE2CAWPfTbzHMQueJTu9tGGKDcI01RjJJIOsR2K2vtjXvrZzY" +
            "alQHs8hd1IIHTF+WRJDJgCsZ30IXDrmH9hgy4A6YB8ISD9weTaIK0BZmONQFEEVOTgzz7MA1dS8KFQxR" +
            "ai1B/W2hgCfKGZWqy2Q4f2TBTRu7TTPnsoPXOmx9fgT3of+U/vYb1u/D6kr4TsfDL/0ZDW1vF6bKGVL+" +
            "dTJlQ2BC/bPFH/zy0d+eOe9nUrlprddfO9/fvay1xwBR4myFDY80ifuydB9hHAGbWDDzsmRhQ8ffvwHm" +
            "a8xPgAKar7P+KwnDDArxPyjt11y/bWvrEKSWmNmsgiVTq9u55PqZCkHAiPyxpFxOS8Ep9d24io3VU6BH" +
            "nR6Rq3VzWfl8ZHU6mbLtpz5mYJuOlt0GShPiVkQEFEQkLVRLAAqwZ8wC6AjwCMo2bQoEdbj5I6n9PyYy" +
            "yTghLYvbxmqBT5OI5aCCOQDuCyK2fLpLcly3nrLlYcPTo8Vs8mYGlmV7qHfD90GcfuofihqqLpodi1Ou" +
            "4/vbsSfnkxuT3mFvZposlxTPMzmLjprXAHdUeA9AD4oKnQpR+BBwEJkGSdM2GEJpAj5HdYb+g9IL4AHM" +
            "CwGRwvwP0yKakSTC48D4FPC6qY1kkvBUD3dXt3uzE2UgTNPrO4UM/HJcuH0aj2uqIf3TVa2G5j9kdEi3" +
            "NPUm4vrlXIxObdndLPWaXQGB2YmXJ994eTmc/cev+qK+a9+5WO3vPUqpPxIKfgzkGMY7HybrP8h2fk82" +
            "/0W42s0pnmi+ewSCZqHp8jFFxTebKVuWG7ds9P9b5t/dP5lf37H7WbInd6oT48WAGHObHZgin1T5XanV" +
            "2n0XhTe81vuk09tekjF+6dH+5a7XuvOjBWyybhmeP2BDbY8Wc6hcCxVGooojOaTq1t1cG4WEwg4oRmOK" +
            "otght2BDsIEdmc4jmZa5ULCC/12Twcu53lG03QYC5lwtBBHiu8NzHRCwaC1Zm99eXNtYYmQAeiKJPGo+" +
            "ZFhqV5RusJ0WcRfIv4xEpwGErQHqd7aRLuWaBChL8gkqXix0GeZQdvjXjSJwNuEk2WpkIn3dXNgmMVMD" +
            "AN2NSOuIgPFqn2uOhDy2SQIX6s7kEURlaWnGb4fFgDvQJVwFPgcE8JLQJgw4em4Cm9k4zGl2TMqjS6ge" +
            "bmQXq93oMneseLAtGvt/sxEMQjC5a067CkJfKs1gBJqPDY9kdctZ6vWHskm0kllYXP7wQeevPsbDxCy1" +
            "B/oQQCkEURAEt2xgQpKIauCD1IaDxYukcF67OR7Jp/+QvrjhPl5AF/lGIWumooMly6Kbd09ttqSJHGin" +
            "EHJaPYGEyMpDLhV7yST6kg+VW91YerxkSSCCXA4rkijhUyl2XM8b7SYxXNtx0GlxHwDYkQeH2TSMUhEV" +
            "+cKmRiqkW449WZvppxJqMpypZFKqND/zFYHUPPAzAi8CJSzXMzBXobW31xvpVRldqxQb/b7A+PwVLmcS" +
            "8ZTyl9+7q+uvvp8wPQoUQ3ZRxBaFTJ4jgkqsDTDBZ4Wbzx4uPPEiH7KH8hp8so9zGVM7tKuUGGY5wRtO" +
            "2zZLuDe4T0F13XWN2rlfBISrmzURI6Zn8xrA32n3h0fyZXy6fXNOiL20GxZN43tenPPWC6mShs7rUw6X" +
            "iqm2z0TTDidjoEe9nUHlD8RF5GffFXiwYpRUyzbjiugjEzPsGSBj8tS3zBYJgCURImGV/CipLsHBwaL8" +
            "ovHw1sMZCrXQ3lDxtszG7v9v9/ylt+7CnWCqhtVI6pz93Fm+/WMeyd1bEKcbmz71lL7c6lBzBtMF8mhA" +
            "7kL2fQlVe2+jbVX/y73Gzs5n0QlysUVEng9TQfHVQTK3SnVgZweXVRVJVpyNMNESUV9QaGCY6o0SzEDy" +
            "xZF0H3B9pFwGXg7UhiIAMgKsh+bTcgIURgKZX20kNrYQSC4ByZH2ppVbfcPT494oMfrzelyUhTZZ7eE3" +
            "9qfryqXZNJyZzCotTujhZjIB88vLJ9arwONBpTVwqrQi7pRxBOA+YQQaYumLh+tEMPeG9Qn2fst6ZjEy" +
            "gkRFUF0ZRaOTshHP3Xtx//H76sKfV8TU5V90yMblUGrbeyfHrEcZ3G1lk0np8by1R291THmZ0YwNYubz" +
            "biqjhezK5WuaXn7pwqw7U5Tmx3LI29vbLfgL2PFdLWlgwtRyIG6juKOIEJogzmhTKPKSQJd4A0CL3oJw" +
            "EeqBKGo1oOsyagYCDXM9VxgD89yt3daB8bzl182z/JDske1jT4RASh4iGH8oJ6wjiHZmqzbbI3jvypwP" +
            "5eYHO/JDT62kVb7Ik/CZEqNJeRBf7C+sTPo9LW+Vt1u7Gw3tV6/VW9XkTZa7U6zt7FZq203e+1uq9nle" +
            "RH1FTZUQcE5FqGHKRTBAVCHAgIiCFGQiVQZeJtlvvGLu4vZFMpXvTUA4ASJNR3nzFbt4MyYKEovLK7tQ" +
            "T1NxZ8/tVXIqOOlDCYeVXdqPL9ZqQNUTZSz9/zkgQfueebH3//E/j2jtHizSE3DDQpTpBU2f0T6t6OAG" +
            "7X0+jcOnHqW3HhsY3gp+kR/JDmIRVdACYlHyAw1E6d0yqIZRB90UIrTvAk/CsFrkcjZxkb4+lsPf+Bjt" +
            "zR6eqPbO7Jnqq/bK1uN+ekcHHhhpZZPx2HbrZ2Oblkz40UwQubbv/ml5xGGDVHl6MsYl/ojiAGqN1phX" +
            "tByWBczhzyEtIcgwfMB3NggbDYaer/34L1Pnzm2ds/df7V/diqgomODoEAkwCg7xFok+kPE/ibO9J3sw" +
            "if3LVcyT143z7PAKghp2pPeQREMvQfRiCfw8De6WE3LCQ2E0GIZe3mx8cO7KvERxZcVHliW57tV59LLp" +
            "255//WJmArBdCsA8oBjWrYZLTyKHlzUDaAFQDXQPi7xCPRKYwB/Q9KLq9LKVjOmAJelVzZrlucdnB2H4" +
            "9Q7gyNz5d7AWq51z95XctxgcaOxp5yxuoNPvusb0ZJVPqA45mVn3uX6RDtBOu+gwctAPSB0vlMz8q999" +
            "V99+j3AcyiKdC3opVuoyjS7BxAG7XC/qB2jokUXxcoj9//u9F3/6aZzy+D4ORXZNRU2HC/oDXSAunQy9" +
            "txiJRNTR/O5lY0Bwm20lO1rRrPdBqxCpK5WmnJK4XXLHc3HQWZ6mgWSAQgKVrywXC0XUyiKx1a2i5nEg" +
            "ZnRpS2EvnR4b3G9hvzMAWyvVZrHliogAx/+kzcfODAVTw5RpBS4dabxr/QFCniQc5IqRaWGfxJOCEo3G" +
            "tKkm5A1OD51lV2toipGS3dItaWwExsuRdOB5OGZTNCKS91xkuxPJKrjMQZkPiC9ppc6Rz40O9o3nVOr2" +
            "3PjBdt2T65WJwoJuOTiWg31ZXY02+gZQFOzo7muZjHfeehXisjhUchvMFIyISFEujp9ewCfafWNhCwCo" +
            "nYGBgBaXJKaAx3uJjHM7xZWn378hfv/5adPPPvPF557kDozbGQ3ib1G2n9G/FNDG9NooQaPlKKWQ9ZOh" +
            "HwZwHKo27BYU2vjg4Jgl4SIC/gL7qI+z7B2ezn14r+MvaAnv3J3ovB1SbhaXfta3fnf7hvfcfbU3rGjF" +
            "xwyHF+33VwyhqLV1610TMKwW81+UhVySaU1QM0KwILBj9m4xJmW0+2bMZkfy8cAtPqWPz2WHxjuTqs3V" +
            "c5CiM16e7SQQJJY3+mNZoEvpBOntp56fOH+x5F76kjXkXDR+vLWP5LaDcRDOxRACzSGQ0YqReakFmUHJ" +
            "Fxk/AXinST+6dAb7idD/yRQZxisAFCRYJv4NeJXmbDCiE1e7sjftvkfkRVH6KVDN+Nv87rZ7l1x1fkXv" +
            "eqcNTidwI8X0xv1nmG7k6UMinat00+ooJWsYTtJVUL1rTa6cBXmB4/+EnCEFwR4Ew0bhBp+sWOK8Jc2U" +
            "sMglwD9YbfpKgKzdGbj05/68ef+5JLLLpnft2c6n0n75iJjLYbNfyLB05Eb4weZjWoc/UY6U4NTi0bb7" +
            "hV6CkfG4e4V6gnDQ44PtZ3s1iPTtbpy3xdSG1eMfWdiZHyqy40O1Mf81DZ36wfeNDk9ChpvubRsAjIhL" +
            "HzwcijGENB93wtMy1VVCRlQ020kDmRjmsQSMmXYumXHZBb8ua/pEk/iEgtgDKWTqgj+gVqWTcooXXCew" +
            "LVJ5eThA1MXv+LcfEYNQoP0HyKtDxDmaRKVJbrkinmC4emaMXVeOnc4oOUmBLsLQaXoigNcml4bdo20j" +
            "Vqw+4xnyFZHrX49vvCF5OdGle9M8bGz+O4Je/P9zYtKe6+87vwQ8rtuLkHftmqWk46B6XJ9zaLvARGJM" +
            "DDH4SEYDEmf4jAWhYfnJFEEYcLUJ2IUTkDamEyJLgi3jJIOIX1flhhIp5tmQuVQyTVdI6ThubCM6A8Ww" +
            "/o/EvvJyHdhKgqnhoeRnaj4wx/MwtB6dI/iAAdU393e0Ul0DPs4urj4T/ML3x27yw3uvigvvuHi0evTh" +
            "be141eaAdkeGS/M7Nuzb3ZUUoS1RhfIbKqY2gHx8YKJsQxS0sBwQLOgbCGXohnKdoHbBF5E9sf4AZwAf" +
            "3lQGerD9B0aLQsMQ9+ZRtkEwAte4aOyQG7HFVj+7POvVBREqRealaD5xdC4N7QU3xI9U/QMyddlT5dcQ" +
            "3YMHMguTnFgSK4pu5bsO7Jvq56R8JwYjR4a2cNpiBRmGN+UfU3tPSg3vqvc25d/OSLH9ilSWoiLSi6ZH" +
            "iXpZCIWi6ugpkAPtuehCINaeVACwsOz2aGX0HUAjr62oy9y6GoW8u1dT/yKJlc7BASTZbHR1XmeB4+ud" +
            "3RQShDjVk8bGNZkqWAaBvDz1tLmJ991x53f/8j1114mMKdl9UFSOUOW/430+LCa3nh+Wu+zIUIngAmZE" +
            "JyC2o+alhqTGpUN6IxyocdYVWf0jwazVy8GAV0AHlqa4UJfF6t3ntV6XPmb49Zasbx+zivcS73kNRXyl" +
            "L3x1zu3vP5VZx05cHh+MhZTVyt1YIdiPrXd6Gmmi1xrmk6t0c6gVWAlLrQcvzWwsinq69V6DxQQbImWP" +
            "0USIAZyN30xw3GIUkyGIAh0IRc+L4s0rwP1qTIwKiFPSZyViBmM026v/bBdearZGNlu5jZrSvUZcft+e" +
            "ftxpRrtlYflykPS5oPK1kNy5RHsavVhZesBpfY9wWiMC6MXCtIBaEi/BzDUFge06oaDGtt5UFjJZZ6Zi" +
            "vtHGSXnis2QbRLyQqeUSs3OjEE4sLREjMapZbkA0fGYhCIM/0ui3tAVJ+IgvYZElkAEAft9pC7MOU9DO" +
            "kCNklCc2wO9PJJx/aDS1CaKSWi+vtMp5eIj+cTKZiep8OWssq3KhJwddO8m3bvWnrXv/nTREZyBme95T" +
            "Ndkuk0OUeTbsBeSD4SndJ/qAvNJSNkcDZuAy/qD9739ilfecAVjvxg6P43qFY18bKjaxPNOmf4Wku6lr" +
            "4rtJ7k3Ndm+1v7ITqNtE2KA6E6PjazS94P+dDkFLLFR60yPpPNJ4QyEVAXwZ103ASS7fRsUMJ+KAWm7l" +
            "juWSwBcwX8pbAatBQbNi/GIYXKjuYQN1uz6pUwCyVnrm4V0LPDd7sA0LTxVbHV2Ws2lZntP9bEpazZAz" +
            "PaCcIf1t8tMjWNtOr8vZSB8YkMurPXppxlefG7uyNFXKKMlIZ4jTDYY4PIwdAE3eKOT0jtqNyh0zy458" +
            "5JYsIRmGLS5xmPaqy4fn7/mIiUeA2AEtEAUtLo6yMpUIe24vmEHdBkoDLs9myUBIjefVjDvhmHGRM4PO" +
            "U03MdvMfzzzG7oaEtIvLCmKulXrIG+DGFdbA3gCUGgbgTswJyeLKFHtvrZyeuXT7/7S0dedN7l/qstKW" +
            "1Ic8YrNDxC4HgYK6BoW/a4KQgAbsgf9whtS/K8e65/ohN6Zj33ivZ/5y/dGrzWTweA50rgUFoZjgzX7l" +
            "vD43x2tPpr59/Gjd82qU7e1SM81/7Ta/XXfIcf++yc+8JY//D3Nsga6OTWeC4PwzEY9m1LL2eRWWwe63" +
            "FNMGpbf6AAdEp4LFUWGefp9PYnSwvGdvh5TJDBeJhmLcRwHrRrNXjEdT8akLcR3XAKKrtQ6IC7woup2C" +
            "/UtHlN9B6g4eK5u/2zJfqhhLVvGumVsWkbVMuqWoVmGbeiuPvC1QYhd10LdJLrBmgZC5vzzcx/66LuOn" +
            "L2XfnNGQLDWGdLE/FAv8IhRzwwq5dq2tPG82BvnyEjINX2+wfQ61v75+C3vvzWRz2y3B5inkUJmp61td" +
            "/TJ0RwoxMZ2OyFzU8VktdWzHXu8CIIZoCw3O33P83KZOALYsJxCJgE1eTgc/AlHQ3gDm1MEC26GHc4dv" +
            "VemnJBhYXDNcE/R71qZ5HenCTlJb41YQYQiDbBZj8QA1CJ+O4SWqWSB1nYNFLT31OHX3PaZv3xfMinhU" +
            "mCukuYnGOYMuuPhIMIb3ys1Pp//MeG/f9Adv1Av57zuny7pT+u2UZl929W3vOctkFO36XcWkVCRIjBLE" +
            "aH1QfMBoSjIgMg8JIbsEBwT6iMTw2BAH0gqUZwFzL0vPNruGVngYwFaMTttUxCFUiFdb3dd1xsfKYA/A" +
            "I7PjGQbnf7GTmv71HK71qi1dXSXZSGbQWwHq9X+aA58SUaSQ86fKics19tomluLK889ssnJXLGovOm68" +
            "847sudtN78BSTTwB6F5mjTfDCHwY7Zydld54d9zm99Mfe+ckV+Mi6PvzXBZqf4nv5uoCUdfd+6B+YkrX" +
            "ouUDjUY1EsA5olSHGotbbaAk8uFVL1Da+dMOWfb/k6zl0Irh9oXGBZ9z1pIK5iIVsvA7cyvXnzUcTxMG" +
            "09tyvoh0iQt/xGsprUUEUnRCQVe9PuixKfQA5BuYIJWkUyCvpIz7RDwHf19um5AVIUuC3f18Nc/u++b/" +
            "+8P4GB8aezUE383PpahzD7QwuaXiHuacR5hOeoQ6z852P5i7vsM/4UmGXnLa9wJOfmWipwITl375CsLs" +
            "5/4wgdT6aRlWrmYHhPtgaVageKFgIwQb1gDokJPi1rA0vwB/IqGgIUXEMYJAkgW4UX6BS8W/g1E6bhuz" +
            "zB1C8RCVEWWfqlHZJMxpdMzomVBqaPpcJNCJml7IPNCuZjNA1jLcqcPquntmUyLMtu2jGIhXi4lMQ4cb" +
            "jSnwJjw83e//7V//sFLUwmUcJwicXqMf4xxf0NCz+4lBqtjrR15vcI18lly4Sh7oacesfh1hlnwb33dZ" +
            "Zdfc7SURdJRdMeTme2ssDiWcCYyCc/2UHpySVkUOHAkieeyCaWnoTa7SXAA0AnHbQ9MJNR8UsUnnCKh8" +
            "grs/ovnH0LhTsbp124xAbpJ14tiigB66AUEGEU3kfG9QlpCHe/pTiEb9/yw2bNimBqJk8CjwrDVM4ABY" +
            "orY7hrwBZQHw7Fr7d69P3ngHz//o+eO/e9zDs/BJvChEIHtdcPqO9jgKVYgO49Nbb51+r6U82c9N/bW1" +
            "8dmipm3L7Mx++T/PEn+/blf/PYn5clytdkPGTYJROndP8HeXtU+te2fy6XKHiO0On0AyYQq9XXEX5BNS" +
            "cBHvb6RS8cAhS3bgdqu66uKDK81NF2VZeq4dNkNZYG6BwuXo2IF4CEMjsClEOkAp9G7VF/k6fIfgIoqh" +
            "jlmO8dssMSJUh1lSGhHXMD9Tdvrdgcb61vNRofmJ6A5GjEcXRxzqsReZsJtV2MHS+XmVmydhO39RXL5b" +
            "OYcVzir7Szr7PP+7Rdc+dm//zQRRDgQsBT9ArbtsIHN0VVUBxketgHwQM5CokI2Bc4HuqJeDoAjCWhBf" +
            "sZdoAJ0tRXqoPRxPORg0SeTVm2PDCzfdAP4A0B1ve8giWXicr054EhQTEvtDn1tM5qNYf5sy5hKk4PsT" +
            "2a9L/c71d7AnhxJAzdX6hpCOpdEMe899uixj938tZ/+0xOEWJBjN5N7Rrjzt6TxJpbZtKql7Y9OPf03m" +
            "ZuI/sO9++IXXqRe5acvq67+bNV+68bl5114/R+8UVDknc4gHVfSMaXb1xjOYGWSyIwVR6cHutPp6vk0/" +
            "RrydqsnC0w2KdU7YPveSDbhOG5fM+FrosAmYhL8uavZ6RRYJKWHDCAIMCl9XRCGgGT4LGXjAJigx8Wci" +
            "mjvdrViRlJFDtQiG+eTcmgMmoG3gySfS+eSyVi10Ud4TozEMW5bM/OFeDqtkmD9ne+79It/+75sBoURP" +
            "FgnTI8hFfpNK8AwnzhVxnDjZK5sTPjinMa1fWaFIa0wsUcELG32NUnkpkcyEK+vaWMFJAQFw8BPwfvyS" +
            "QVACkgLOGIsnwGe7fStUhZRxdeaPcRqJqn0EfceqC6bjnFgDZpmIKFRl4ggUSjwLDIAnMH3PUoQ4KBhG" +
            "FNoVXN8n9Y4+kouWi0gzYz3GEdWgcwB1kSUOSR3QkCwkRVBNjLZeL6QIqR+881XfeyP3z47PYrKzJDTD" +
            "PM4y+zQeoihAqaiM43REpk9mrjEzFxxpnvf+vqrT5Gf7ui8h9qJUMOj6dfOES6YHjwD/MUjPNORwjoqM" +
            "eII2QRPhM+jM44gG10LRZ6AB9O8jQ2Zm66MCeC2EQXGdSaXjNHJ8ANkY3TxPDcIHOgM9g9gSL85n4rVu" +
            "47lBSMZtTdwRXd9Qr1XFMECYlq3bWjaRCkFNLta7WZScdz/wjMnTi8sEzLBC7TM4qlw6tCuEuMY4/WcP" +
            "mkdm6gu5RfNRO1sJn6NzjkhU1G8XugS4+b3XvbKKw4DpxZTdEVuo9pUJV7i2bWtmmkgIxBFDHLxvmFZm" +
            "hWUcvR16U5roEhSMZtutGiJLhXjmuW1+2YuIUJzoC8NXM91M0mVQhWwQ1SRVELBBCBDIKEhKSGfRy9f2" +
            "K5hqyID0+Wzsu0EwKvFLJuRFVE61zd6xE2JTNJjkPc9TJ1IgUHQ3Nl51xs+QxKjk1e8UaXUClkDlufC2" +
            "jHO/TbDE7ubXLh2bJGkP0TKUxdxh97a3Hkg1vlWsv94hZDu637vqsMHp2GhTk9DOs1l43TCYGq6gIlhC" +
            "Gf+IGaMHPaKYaCwmhB4VsB0avbNW/65yaQMu/b7DpAr/e4sfQEYxmTczSM3I0JpIoYrwjiAWfAfm/7HC" +
            "n1H6/hA/xSIuD6DdB96borrp7mWGuyk2YYcDkKvSYIuT6wkP0hzbdauiYyriIJuAEwDbHJ/fNt53/3CW" +
            "6YmC3RJxKkw5nMs2fJs0jy5p3J6coUItTeJhc8F/F4PWIFxLHOrfdNrD37kM7cqyJa8IImCadFvoksif" +
            "DXERMZjcU8sDsjrvCDJeKt8UOGCKutWeL8hMZDHhREVFHqOBWxGeAoiawEFMSFGiNClQMss5u6BU48pk" +
            "tzu64ogIqF1dAuVJRmXASfh5Jl4XBtontW7oPgDJTxBDItFJDA6w5hMaCN8fJJzSbrrzjaFGzvczHqte" +
            "WZx/bPv/vwd3/rwu995A1AHYE/Q/imrfwSzbG4njn3qSOUe4S0g4p9I594uJ1IkLksL364ZHzv25e9+7" +
            "pzzD2cSomYiY4apWKyFRGwYIHGiKMYV2TJ7htWaS5xMiVvL3VcbJJdOqI7tYpJ9Tg04CVmGWpNjQIbB3" +
            "TiOrmPClF3NQUEEfNYtl3IFx7XhACwPC6Oy0dnAAaZZjFYV8FeNxXWvZHrztn+u4V7kOpOMuxM6Hd+TH" +
            "eZiPXhlz5sJ6MtOf/nMxsbaNk0yNEFwgdMI9RcZdzlwSePEeO2F8ko3WJU45cgkl8kwKke2ZefB8Prg0" +
            "Mf/4r0z02MxWfIp1oRJKYVOMvURYSXHbiTCiu/7Lhsn0kTb37tjH3blyUAutF21F8YtPseKIGAcxbphC" +
            "A3h2DCbLNCvnwP1weC8wJqWSycEFwzTSsUpvO6CK8u4Ve7oDsp3Mib3+iZYSCqdPWVc+4Jz2zH5I6cyH" +
            "+pLr4M8Hk807pr11G2r6fetc2905RLLuD/+p3vv/OzPCTkTrRPwgX6KtK5jg69wPKl/P7/yzsLXHnc/l" +
            "mfZ+YPp4oSaiG0fd1+88c4j8tQb33LNnj3jyM1d3YITqrI4MJ1J6Tfnpd5zmL95lvxQs3zCycl0tuXvW" +
            "dMOSJKakFkdVDR6ZQuDKfQrr3BhSo9gRiiG8ISCCF2R5+KKNNDhbqAKAWyd6msGUiIwg2YYlm2VM6oNB" +
            "xpopVwMPtnuanCeVBzJCpUMGNxGiuol7mwl3tE1Q8/Ry4U4ikGrY56oaO9833k/+tl3Lr30CDguA/d3S" +
            "WextPnY/HJPOJFVnMsOk6tmlT9o89lu9yHj4lb2E3/1mX0Hp4AKerrhOE4mznPEVLzNAjkhh5tgAaAIf" +
            "KCVueWR4FjKea4YM4u5dN+0aTXOSJkEXJDYrqtpVpIuxHL9gQX9ZZHt9nXP87NJ1fHh9mY+C2LngyDBC" +
            "0KOoTuKELwBmJpSDZQstFByTPtEhCRqpPWNrjAO+PkOP4lCThcl6RtbeA1L1nbm9o9fd+1rzj37AG5hQ" +
            "wsK955Kr7+teNePuA9lhYW5+eLRqdTlNbbYrt/wxIFW5oa3XT2zd4ISMrqaiEf7yIVF7zdz7q1x+8cM/" +
            "XoMkcKfzvk3zdk37tWvL7gv0ncSDIotQCNKis+CjdBXqijKIMCRIrT+MqhJlDpBNsr9aE/ICuOHg4GWi" +
            "JYtdd2Io+LwfLutI28D0IFnwg3SSaXV0xo9DbCSkkZGhBAu6IqlxSVOlqRqa7C6Wt1e36JAMmJuodci3" +
            "V/0V56qPJxeOiO/SMLOa+bJOTPClMexnnlfMP6C+uE/v/XoRQdjMcn2/bamA9WKAlzadAJJ8+cG3vvbw" +
            "aea/qc890LiZY3wlm740Q7zSc3NGLoFSqdK7GAAR3TxPHh1TBWApTzHScZEBBRydQoDskx/oMESELLb7" +
            "WE6MLNsXJV7AwvTm4qruukCggBdo4aBgkBVTNsA2FONJWKqLHEUtXsO45GYwGRiPK3pvp9Jyj//6SPvu" +
            "fHrhJwAqSIMHzoNZvAOffEbO+879Ngdwm1kcO/MRG5uioxznhhu3PhI/hfOVddeMntgGtWAZXlFUdoD2" +
            "/PYfDplufwmOXsr/77VxM1n+Gttb9Jzz91k//CMcPNJ9m09eT6REHWHDIwwlcR9sh9yAMS64ScSKieIr" +
            "Z4ZfeWdpxTKD9MpFcDTMN1UJgUYyCKz4QeOCUvigEI6oOeAvq3EfESr9oA9MAvBTnM6gAo/1eE/bngyM" +
            "BliBo2gJpZuXfCq8gOP//IPbjwsDH6urTyw+LOpY09d+EBSXLryCHnrNVIcE+90H1uzH1+56uZrDlxyI" +
            "JFAWsFD4YdgjvA3JFEGaJFB/uRFC6wZ1QvsxrUCR/U4FaiB51ygAvq/Rhz9HwbcjI2SPcr66DEKBKoMP" +
            "lHDabpnAPLg3dCOYkw8AeN5Dv3fRYqeTQvhTr8OhMwFEAufQWDgF0AUnAkTgh2B0U0eXcvc0vIE3TRAR" +
            "zA+XMg0rHxWuugVh+f3pTj7vW7t/6nfXn7hK9LHNf+7pVJmbtaNx5BRgzsWpG+fuuqaC4+8Yh5OCE4HH" +
            "6MrFaGfUOhrnYHlYhokiddt0w9B8Qj09n3B5+h/VklAVshAhgXkiyA0TOju4y5RACtkDdNGWkJowAC2Q" +
            "/85F1kF8BFPgW8aOrg6JZIwIwOd8VhB4Gy4lefKMuIc9sYEQmFQTZq3cIBGGgOYLuLKfKgIEMUJwVGjb" +
            "xG3tyt2/S5r/T+27j73zAPnPkCCE6+e4N96YTIrW4xtLK2OLa1/8Rs3/v1/fPCcI5Oj5SzsQs1DF5pob" +
            "kGlRf5DcHquj3RNF9novy27MD9NoKwQMCywEGQBooLTYZckWB0hjHRFWS9IIkayLAvOCF08l2I1RWBBj" +
            "iEnZoSEHmUklDBRioxyT/+xGA8ROYb6OKwa4Vi0Uz3pjg+aAannwOzUdwLqMYClHtN65nTo3O70/q77q" +
            "Vj1rzOfJv6d6VRuajxMxijjOb7qP7p41pG5oxccKhbSibiMgXEn3SBnlKUhLswF0bENqQ+NIWKzLOKc9" +
            "oIPoyMsBv3QD6aiAlFxqBdj6mCVgK4H0BSNQXAGXkV7wDfh+ZD18cWHhrrQO6Ph8fmSBLtbdAJBho0YG" +
            "xu1MrV4QO76wYObmzs3vWHfeMaafuYL9Ypw57+NriYL3z9rTqEexPaq26TZ+4c/ef30ntFiOaeq4nBJI" +
            "BqIGpcK+9LAMBX+onX3auAnzA2G4QfKLJ1+EKqXBYg+4YT4E6mEncpM/0bOOeyBS9iibnRoCBRJTu+n+" +
            "1CzYb+onW7RvXjccARs0cC7Y5GFF1eeve+p+Vl+fl8yfCqjfVb9QY39bkxI53KhJFmdQXazTo4tTU2X9" +
            "uwbVxSBAkA6ucONHg6TYfSwSIboQTij4zNsT57tylO0xqJK01Y618N70S8yFTUYjl6Sb/dvNMLuXzpud" +
            "FtkS9o2XNdEe+TG0VOHdh5u0RNwhaa+4Q3YolFCYNEY1xe6/8Y0v/utZubr0zPelefFEvngudPaMyfse" +
            "47/2R9f/cvH/7o4mqFMG1MU3ft/bf9HUoy+O/jweZEYNIdHb9Aprth97Et9qGj0cLfxpZH+S2PUFilAF" +
            "aIv69A0HCA6xqXdTnAEnNDZi+Jn9yJ9wPBkdxNEzuwYRv1+Y+fX97adb7JcLxGXFMXdaI+b+txhbmJqZ" +
            "HZuUo3Lw7l8ecPhy/710hRTF6OX8BnNzO7T6NGujPTsJYPRLXJg7FSJ4U5v35WXenN0NdKHDoEYfpD6A" +
            "+1DHx/hbvSlwU+bqKvsWppOwu4zcONwJMYNmH/+hx994wt333JdWuWCH9zl9zBMMU5MmwzW/vrLH37V5" +
            "eeqqqzQd7PDCcVGR8EDoB0OaGDRbfdiJGJ0RC/Sh9LwGz6Xbi+NMWzCzfQ7GpGi0UfUSCn07nm00YCOn" +
            "omWCHjsbsOruCHSlM4CvfulT6rk7ikVg86b5fo9AH6KrKV/vVu6467kocunL7tq6vIj2SsvHjvrnCPl0" +
            "UKxlJdVgKHdgXBvNIeRvHTGhxYb2uT/2qhn0faXnzvcozGwRTdFJ1QZ6oXRXfQB0bZ7Q/RLm+lf5IGQe" +
            "eTUA/TOyIy0RNHH4Jh6GB0nGjYaB9vQAaOJg8IkPHm6/uCTm4/++qmTDywRRn3jW2c+dPt1iqoMhcVdk" +
            "iwJKNZ0wyk1FB1mV2y67Ur3X7bhnL/cHglJb6DDDS9F0gy70M4QhB5hpwU1kg4QYrc9UpgeYMYpwse1h" +
            "xfupzdQCYFkqLZI3BgseirVkQYwPaR9ho+hg9KywSycrDz17IYz6AKt8RJfLmevuuJc6AinpopRqhJpG" +
            "W0vKzw8pRtVhP5GF4cHkcDR4bDfUOrda7tt/2cEdB4qTf2e+lz0QY2ODcAUj6RH6IVm+ooETb859mtqj" +
            "KFi+Bv9oQ+ii1qRo9Dm3WSCBw+NNHwqxXXRIjMa0AXeESGJaHbQY2hL6he7266yw+v4peJELdh2j6h4u" +
            "9eGo9ALtAl/hvcNT3Z7oxOOoQ2tdfTHp54XXUJrNAPRERSm0U773//ifUPFqF74RRMVGWPTUN7Vn57jl" +
            "438nB6//Bdd6Cj0EdG3JocXo42evXQ83IZ3DT+ijVoAP2iAVENBse3+Re9o6KHUw1batqsH7Ycf9KHZB" +
            "72i/AUthxeiBnpKO9NetBv2lxIanYXdqQA0o9foOW2B69PVedpGFwaGjVEzmuhKE+Audj/waONwWNxKf" +
            "XR3j1TAXA1HHApMb6fhie7DodA87I8P6sg4QxEYXh12jhSJNjoeGnBHJET0S58adaKjRHrQxXA0InqHp" +
            "9HEItqiPrgDKtG7dkWlcBzP9Knn43k4ocNGIw+vUHkiOYaXqCxRt2EPnEXD4FI0VVEvPBVHOBvOKN2oP" +
            "vSYTmW0U2lpt5c6YIuOhyJhj8YabrSZblTHly5En/S5GIz2ppeGcx/9EvL/A8JJbeU9rvBEAAAAAElFT" +
            "kSuQmCC")]
        public string Image80Base64 {
            get {
                return ((string)(this["Image80Base64"]));
            }
            set {
                this["Image80Base64"] = value;
            }
        }
    }
}
